### PR TITLE
[DESK-762] share user fix state check new services

### PR DESCRIPTION
**Pull request by mauricio0000**
### Description

Sharing a second user in the device incorrectly detecting shared-to state

### Test plan

1. Sign in
2. Go to a device
3. Click on share device
4. Select a user
5. Select a second user
4. You should see the combination of services and scripting 

### Ticket

https://remoteit.atlassian.net/browse/DESK-762

### CODE REVIEW

**Review by JamieRuderman — CHANGES_REQUESTED** [review]
Looks really good. Only question is if we could show an "indeterminate" state if two users have different permissions for the same checkbox.

image

Let me know if you want to discuss. _Thanks!_

**Comment by mauricio0000** [comment]
https://github.com/remoteit/desktop/pull/302#pullrequestreview-533795350 I am giving priority to the value `true`. what do you think @JamieRuderman ?

**Comment by JamieRuderman** [comment]
@mauricio0000 Let's discuss. Maybe we can't do the indeterminate state.

**Comment by JamieRuderman** [comment]
@mauricio0000 Let's discuss. Maybe we can't do the indeterminate state.

**Review by JamieRuderman — CHANGES_REQUESTED** [review]
@mauricio0000 All looks really great. could you just check that the indeterminate state applies also to the "Allow script execution" checkbox? Code all looked good too. Thanks!

**Comment by mauricio0000** [comment]
@JamieRuderman thank you for the review, I just add indeterminate for scripting

**Review by JamieRuderman — CHANGES_REQUESTED** [review]
@mauricio0000  It all looks good! Working great. 
My only request is to change the component interfaces to replace the "set" commands with "on" commands. Let's discuss! Thanks!

**Review by JamieRuderman — APPROVED** [review]
Looks good thanks!

**Pull request merged**
