### PR TITLE
 DESK-867 filter platform

### PR DESCRIPTION
**Pull request by JamieRuderman**
### Description

Filter devices by Platform

### Ticket

https://remoteit.atlassian.net/browse/DESK-938

### CODE REVIEW

**Comment by JamieRuderman** [comment]
@mauricio0000 Working great - but noticed that the "All" option doesn't select. Could we fix that please?

Also I got this error when clicking on sort by "State".
image

**Comment by mauricio0000** [comment]
@JamieRuderman could you test again?

**Comment by JamieRuderman** [comment]
@mauricio0000 the sorting error is fixed and it defaults to **"all"** checked but when I click **"all"** it doesn't highlight.
image
It should be blue with the check mark.

**Comment by JamieRuderman** [comment]
Approved! @mauricio0000 You are the reviewer - so have to do the actual approval and merge.

**Review by mauricio0000 — APPROVED** [review]

**Pull request merged**
